#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamNativeShowcase.Droid.Resource", IsApplication=true)]

namespace XamNativeShowcase.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Resource.Attribute.MvxBind = global::XamNativeShowcase.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Resource.Attribute.MvxDropDownItemTemplate = global::XamNativeShowcase.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Resource.Attribute.MvxGroupItemTemplate = global::XamNativeShowcase.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Resource.Attribute.MvxItemTemplate = global::XamNativeShowcase.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Resource.Attribute.MvxLang = global::XamNativeShowcase.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Resource.Attribute.MvxTemplate = global::XamNativeShowcase.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Resource.Id.MvvmCrossTagId = global::XamNativeShowcase.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Resource.Id.MvxBindingTagUnique = global::XamNativeShowcase.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Resource.Styleable.MvxBinding = global::XamNativeShowcase.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Resource.Styleable.MvxBinding_MvxBind = global::XamNativeShowcase.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Resource.Styleable.MvxBinding_MvxLang = global::XamNativeShowcase.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Resource.Styleable.MvxControl = global::XamNativeShowcase.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Resource.Styleable.MvxControl_MvxTemplate = global::XamNativeShowcase.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Resource.Styleable.MvxExpandableListView = global::XamNativeShowcase.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::XamNativeShowcase.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Resource.Styleable.MvxListView = global::XamNativeShowcase.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::XamNativeShowcase.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Resource.Styleable.MvxListView_MvxItemTemplate = global::XamNativeShowcase.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int esri = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public const int MvvmCrossTagId = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int MvxBindingTagUnique = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int button1 = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int textView1 = 2130968578;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Splash = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int View_Map = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int View_Tip = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
